export const PAGE_SIZES = {
  DOCTORS: 6,
  CONSUMERS: 8,
  PAYMENTS: 10,
  PAYMENTS_EXPORT: 100,
  AUDIT_LOGS: 15,
  AUDIT_LOGS_API_DEFAULT: 20,
  ACTIVE_DOCTORS: 100,
  LEAVES: 20,
  EMP_SEARCH_RESULTS: 6
} as const;

export const DEFAULT_PAGE = 1;
