export type { BillingPlan, Payment } from './billing.interface';
export type { ConsultationChannel, ClinicLocation } from './clinic-location.interface';
export { CONSULTATION_CHANNEL_LABELS } from './clinic-location.interface';
export type { Consultation } from './consultation.interface';
export type { ConsultationAttachment, ConsultationAttachmentKind } from './consultation-attachment.interface';
export type { Disease, DiseaseInfo } from './disease.interface';
export type { Doctor } from './doctor.interface';
export type { DoseEvent } from './dose-event.interface';
export type { HomeopathyApproach } from './homeopathy-approach.interface';
export type { Message } from './message.interface';
export type { Prescription, PrescriptionItem } from './prescription.interface';
export type { Role, User } from './user.interface';
