CREATE TABLE "HealthService" (
  "id" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "shortTitle" TEXT,
  "category" TEXT NOT NULL,
  "expertTypes" "ProviderType"[] NOT NULL DEFAULT ARRAY[]::"ProviderType"[],
  "summary" TEXT NOT NULL,
  "description" TEXT,
  "priceInPaise" INTEGER NOT NULL,
  "compareAtPriceInPaise" INTEGER,
  "durationMinutes" INTEGER,
  "imageUrl" TEXT,
  "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "includes" JSONB,
  "outcomes" JSONB,
  "whoIsItFor" JSONB,
  "howItWorks" JSONB,
  "faqs" JSONB,
  "relatedDiseaseSlugs" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "seoTitle" TEXT,
  "seoDescription" TEXT,
  "isPublished" BOOLEAN NOT NULL DEFAULT true,
  "isFeatured" BOOLEAN NOT NULL DEFAULT false,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "HealthService_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "HealthService_slug_key" ON "HealthService"("slug");
CREATE INDEX "HealthService_category_idx" ON "HealthService"("category");
CREATE INDEX "HealthService_isPublished_sortOrder_idx" ON "HealthService"("isPublished", "sortOrder");

ALTER TABLE "Consultation" ADD COLUMN "serviceId" TEXT;
CREATE INDEX "Consultation_serviceId_idx" ON "Consultation"("serviceId");
ALTER TABLE "Consultation"
  ADD CONSTRAINT "Consultation_serviceId_fkey"
  FOREIGN KEY ("serviceId") REFERENCES "HealthService"("id") ON DELETE SET NULL ON UPDATE CASCADE;

INSERT INTO "HealthService" (
  "id", "slug", "title", "shortTitle", "category", "expertTypes", "summary", "description",
  "priceInPaise", "compareAtPriceInPaise", "durationMinutes", "tags", "includes",
  "outcomes", "whoIsItFor", "howItWorks", "faqs", "relatedDiseaseSlugs",
  "seoTitle", "seoDescription", "isPublished", "isFeatured", "sortOrder"
) VALUES
(
  'svc-general-health-consultation',
  'general-health-consultation',
  'General Health Consultation',
  'General consultation',
  'Medical Care',
  ARRAY['DOCTOR','SPECIALIST']::"ProviderType"[],
  'Online consultation for fever, cough, pain, infections, digestion issues, allergies, and everyday health concerns.',
  'Share your symptoms, history, photos or reports, then get expert guidance with prescriptions where appropriate and follow-up support.',
  49900,
  79900,
  20,
  ARRAY['acute care','prescription','follow-up','online'],
  '["Symptom review","Prescription where appropriate","Follow-up guidance","Care escalation advice"]'::jsonb,
  '["Clear next steps","Safer self-care boundaries","Treatment plan matched to your concern"]'::jsonb,
  '["Fever, cough, cold, pain, stomach upset, allergy, headache, or general health concerns","Patients who need online guidance and follow-up"]'::jsonb,
  '["Book online","Share symptoms and history","Expert reviews your case","Receive guidance and follow-up"]'::jsonb,
  '[{"question":"Is this for emergencies?","answer":"No. Severe symptoms need immediate emergency care."}]'::jsonb,
  ARRAY['fever','cough','digestive-problems','allergy'],
  'General Health Consultation | HopeHub Care',
  'Book an online general health consultation with HopeHub Care experts for common health concerns, guidance, prescriptions where appropriate, and follow-up.',
  true,
  true,
  10
),
(
  'svc-psychologist-consultation',
  'psychologist-consultation',
  'Psychologist Consultation',
  'Psychologist',
  'Mental Wellness',
  ARRAY['PSYCHOLOGIST']::"ProviderType"[],
  'Structured online support for stress, anxiety, mood concerns, relationship concerns, behaviour patterns, and emotional wellbeing.',
  'A private online consultation focused on understanding your concern, current stressors, patterns, goals, and next-step care plan.',
  89900,
  129900,
  45,
  ARRAY['mental wellness','stress','anxiety','therapy','online'],
  '["Concern assessment","Personalised wellbeing plan","Coping strategies","Follow-up recommendation"]'::jsonb,
  '["Better clarity about your concern","Practical next steps","Referral guidance when needed"]'::jsonb,
  '["Adults or adolescents seeking emotional support","Stress, anxiety, mood, relationship, confidence, or adjustment concerns"]'::jsonb,
  '["Choose this service","Share your concern privately","Expert consultation online","Receive a plan and follow-up guidance"]'::jsonb,
  '[{"question":"Can I choose counselling or psychologist support?","answer":"Yes. Use filters or this service page, and our team will match the right expert type."}]'::jsonb,
  ARRAY['anxiety','stress','sleep-problems'],
  'Psychologist Consultation Online | HopeHub Care',
  'Book an online psychologist consultation for stress, anxiety, mood, relationship, and emotional wellbeing support.',
  true,
  true,
  20
),
(
  'svc-counselling-session',
  'counselling-session',
  'Counselling Session',
  'Counselling',
  'Mental Wellness',
  ARRAY['COUNSELLOR','PSYCHOTHERAPIST','LIFE_COACH']::"ProviderType"[],
  'Online counselling for life stress, family and relationship concerns, career stress, habit change, and emotional support.',
  'Get a focused counselling session that helps you express the concern, identify patterns, and leave with practical next steps.',
  69900,
  99900,
  40,
  ARRAY['counselling','relationships','career','stress','online'],
  '["Private listening space","Goal-oriented counselling","Practical action plan","Follow-up recommendation"]'::jsonb,
  '["Clearer thinking","Supportive guidance","Next steps you can apply"]'::jsonb,
  '["People needing non-emergency emotional guidance","Family, relationship, workplace, career, or life stress concerns"]'::jsonb,
  '["Book a counselling slot","Share your context","Speak with an expert","Continue with recommended steps"]'::jsonb,
  '[{"question":"Is counselling only for illness?","answer":"No. Counselling can support life situations, stress, relationships, and behaviour change."}]'::jsonb,
  ARRAY['stress','relationship-stress'],
  'Online Counselling Session | HopeHub Care',
  'Book online counselling for stress, relationships, career concerns, family concerns, and emotional support.',
  true,
  true,
  30
),
(
  'svc-dietitian-nutrition-consult',
  'dietitian-nutrition-consult',
  'Dietitian and Nutrition Consultation',
  'Nutrition consult',
  'Nutrition',
  ARRAY['DIETITIAN','NUTRITIONIST','DIABETES_EDUCATOR']::"ProviderType"[],
  'Online nutrition guidance for weight, diabetes, digestion, lifestyle, sports nutrition, and long-term food planning.',
  'Review your routine, food pattern, goals, medical needs, and preferences to get a practical nutrition plan.',
  79900,
  119900,
  35,
  ARRAY['nutrition','diet','diabetes','weight','digestion'],
  '["Diet history review","Goal-based nutrition plan","Food preference mapping","Follow-up checklist"]'::jsonb,
  '["A practical diet plan","Better routine clarity","Nutrition guidance matched to health goals"]'::jsonb,
  '["Patients needing diet support for weight, diabetes, digestion, fitness, or general wellbeing"]'::jsonb,
  '["Share food routine","Expert reviews goals","Receive nutrition plan","Track follow-up"]'::jsonb,
  '[{"question":"Will the plan consider my food preferences?","answer":"Yes. The consultation captures routine, preferences, restrictions, and goals."}]'::jsonb,
  ARRAY['diabetes','obesity','digestive-problems'],
  'Dietitian and Nutrition Consultation | HopeHub Care',
  'Book an online dietitian and nutrition consultation for weight, diabetes, digestion, lifestyle, and practical food planning.',
  true,
  true,
  40
),
(
  'svc-physiotherapy-consultation',
  'physiotherapy-consultation',
  'Physiotherapy Consultation',
  'Physiotherapy',
  'Rehabilitation',
  ARRAY['PHYSIOTHERAPIST','REHABILITATION_SPECIALIST']::"ProviderType"[],
  'Online physiotherapy guidance for pain, stiffness, posture, injury recovery, mobility, and rehab planning.',
  'Discuss your pain pattern, mobility limits, history, and goals so an expert can guide safe exercises and next steps.',
  79900,
  119900,
  30,
  ARRAY['physiotherapy','pain','rehab','mobility','posture'],
  '["Pain and mobility review","Exercise guidance","Safety boundaries","Follow-up plan"]'::jsonb,
  '["Safer movement plan","Reduced confusion about exercise","Clear rehab next steps"]'::jsonb,
  '["Patients with non-emergency pain, stiffness, posture issues, injury recovery, or mobility concerns"]'::jsonb,
  '["Share symptoms and photos/videos if needed","Expert reviews movement limits","Get exercise guidance","Follow up on progress"]'::jsonb,
  '[{"question":"Can online physiotherapy replace emergency care?","answer":"No. Severe injury, weakness, numbness, or sudden pain needs urgent offline care."}]'::jsonb,
  ARRAY['back-pain','joint-pain'],
  'Physiotherapy Consultation Online | HopeHub Care',
  'Book an online physiotherapy consultation for pain, posture, mobility, stiffness, and rehabilitation guidance.',
  true,
  true,
  50
);
